### PR TITLE
Add F1 conversion class

### PR DESCRIPTION
**Pull request by markim**
We are adding F1 from the assignment list https://github.com/igorsteinmacher/CS499-OSS/blob/master/assignments/PRcodeReview.md

Here's a running todo list of things we should add before the merge happens:

- [ ] Add .gitignore to ignore .class files
- [ ] Separate the right pieces of code into the characteristic() and mantissa() functions

### CODE REVIEW

**Comment by markim** [comment]
One thing we can add for this PR is a .gitignore that ignores all ".class" java build files. This will prevent clutter in our repo.

**Comment by B-Finley** [comment]
One suggestion I have for what we can do in the characteristic and mantissa functions is to move the code that is used to parse the characteristic and mantissa values from the main into those functions. This way we can also determine whether the characteristic or mantissa parsing occurred successfully by returning the corresponding boolean from these functions.

**Comment by igorsteinmacher** [comment]
I liked the comments here :)
Group 10 will review this

**Review by ljburbank — COMMENTED** [review]
Overall, the design of the code could use some work. This is mainly in how the code is not broken up in a way that helps it stay organized. You have mantissa and characteristic functions, and you call them in the main, yet you put the code calculating the mantissa and characteristic in the main and left the two functions empty. Now when someone calls one of the functions with an input number, they do not calculate anything. The calculations could be moved into each function, which would also declutter the main function. One other function that could use work for this is NaN(). As of right now, all it does is print a single line, meaning the function call could be replaced with a single print that is easier to understand what will happen when initially reading over it. This only really makes the readability a little slower, since you have to look at what NaN() does, and it is only a single print that is just as understandable in the spot.

One other piece that could possibly be looked over is the return statements. The main function is set to return nothing (void), yet it has many returns that are not necessary. This also ruins the purpose of the while loop, since the main function will always hit a return and stop before it hits the end of the loop to go to a second iteration. This causes unreachable code, which makes either the code unnecessary, or the return statement that makes it unreachable unnecessary.

**Pull request merged**
